//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindJobApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyImage
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public byte[] ImageContent { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
    }
}
