//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindJobApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyProfile()
        {
            this.CompanyImages = new HashSet<CompanyImage>();
            this.JobPosts = new HashSet<JobPost>();
        }
    
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateEstablish { get; set; }
        public Nullable<int> CompanySize { get; set; }
        public string CompanyLink { get; set; }
        public string Reason { get; set; }
        public string Overview { get; set; }
        public string TaxCode { get; set; }
        public string BusinessLicense { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyImage> CompanyImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPost> JobPosts { get; set; }
    }
}
