//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindJobApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.UserApplyJobs = new HashSet<UserApplyJob>();
            this.Skills = new HashSet<Skill>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> RecruitmentNumber { get; set; }
        public int Salary { get; set; }
        public string Description { get; set; }
        public string Requirement { get; set; }
        public string Prioritize { get; set; }
        public string Benefit { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string Address { get; set; }
        public int YearExperienceId { get; set; }
        public int LocationId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
        public virtual Location Location { get; set; }
        public virtual YearExperience YearExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserApplyJob> UserApplyJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
