//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindJobApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEducation
    {
        public int Id { get; set; }
        public string SchoolName { get; set; }
        public string Major { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string Detail { get; set; }
        public int UserId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
